version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: mysql-blog
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: clebson
      MYSQL_PASSWORD: senha123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress-blog
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: clebson
      WORDPRESS_DB_PASSWORD: senha123
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
  wp_data:

